version: '3.8'
services:
  
  rabbitmqmessagebus:
    container_name: rabbitmqContainer
    image: rabbitmq:management
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      - semester7project_network
  mssql:
    container_name: mssqlContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPass!123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - semester7project_network

  elasticsearch:
    container_name: elasticsearchContainer
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
    ports:
      - "9200:9200"
    networks:
      - semester7project_network

  kibana:
    container_name: kibanaContainer
    image: docker.elastic.co/kibana/kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchContainer:9200
    ports:
      - "5601:5601"
    networks:
      - semester7project_network
    depends_on:
      - elasticsearch
  influxdb:
    container_name: influxdbContainer
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dev
      - DOCKER_INFLUXDB_INIT_PASSWORD=devpassword
      - DOCKER_INFLUXDB_INIT_ORG=devorg
      - DOCKER_INFLUXDB_INIT_BUCKET=devbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken
    ports:
      - "8086:8086"
    networks:
      - semester7project_network
networks:
  semester7project_network:
    name: semester7project_network
    driver: bridge