version: '3.8'
services:
  
  rabbitmqmessagebus:
    container_name: rabbitmqContainer
    image: rabbitmq:management
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      - semester7project_network

networks:
  semester7project_network:
    name: semester7project_network
    driver: bridge